<!DOCTYPE html>
<html lang="en">

<head>
    <?php include 'header.inc'; ?>
</head>

<body>
    <?php include 'menu.inc'; ?>

    <div class="container white">
        <h2>Enhancements 3</h2>
        <div class="container" id="margin">
            <ol>
                <li>
                    <h4>“Quizzes” table in DB and dynamic HTML generated by PHP</h4>
                    <p>On the screen of quiz.php page, PHP is used to operate the question and and answer 
                        by processing and inserting html so that it generates the correct html code to suit 
                        each type of question.</p>
                    <p>This will make the code more general, thus adding more questions is way easier.</p>
                    <p>Application on website: <a href="quiz.php" class="a">Quiz Page</a></p>
                </li>
                <li>
                    <h4>Table to save supervisors' information and login</h4>
                    <p>Create a table of “supervisors” including information such as id, username, password.</p>
                    <p>Supervisors only work with the system when logging in with the correct username and 
                        password. When entered incorrectly, a counter variable will be incremented by 1. 
                        If entered incorrectly more than 5 times, an error message will be displayed with a 
                        message waiting for login after 3 minutes. After 3 minutes, supervisors must enter 
                        the correct username and password to be able to log back into the system and the counter will be reset = 0</p>
                    <p>Source: <a href="https://www.youtube.com/watch?v=arqv2YVp_3E" class="a">Login system using PHP with MYSQL database</a></p>
                    <p>Application on website: <a href="form_login.php" class="a">Login</a></p>
                </li>
            </ol>
        </div>
    </div>

    <?php include 'footer.inc'; ?>

</body>

</html>