<header>
    <div>
        <h1 class="color">
            <a href="index.php">WebGL - Web Graphic Library</a>
        </h1>
    </div>
    <nav class="nav" id="index">
        <div class="row">
            <div class="col s12 l3 center-align">
                <a href="topic.php">Topic</a>
            </div>
            <div class="col s12 l3 center-align">
                <a href="quiz.php">Quiz</a>
            </div>
            <div class="col s12 l3 center-align">
                <a href="references.php">References</a>
            </div>
            <div class="col s12 l3 center-align">
                <a href="enhancements3.php">Enhancements 3</a>
            </div>
        </div>
    </nav>
</header>